name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: blog-test
      uses: benniaoge/blog-test@master
      env:
        ACCESS_TOKEN: ${{ secrets.BLOG_SECRET }}
        TARGET_REPO: benniaoge/blog-test
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://blog-test.benniaoge.com